alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress: {}
name: worker-freegpt-agent
region: lon
workers:
- dockerfile_path: ./Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: dev0xx1/freegpt
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: worker-freegpt-agent
  source_dir: ./